#Hugo configuration
title = "1e3243"
baseURL = "https:\/\/3rsdf.asdf.df"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758823"
subfolder = ""
firstpartycookies = true
cookiedomain = "asdf.df"
